# -*- coding: utf-8 -*-
"""FINALPROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AlIgRzmjkWq1T4H55-yq_aHnEcKI9RnP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(42)

rows = 1000
data = {
    "Income": np.random.normal(50000, 15000, rows).astype(int),
    "Spend": np.random.normal(20000, 8000, rows).astype(int),
    "Region": np.random.choice(["North", "South", "East", "West"], rows)
}

df = pd.DataFrame(data);
print(df.head())
print(df.info())
df["Income"] = df["Income"].abs()
df["Spend"] = df["Spend"].abs()

print("Missing Values:\n", df.isnull().sum())

print("\nData Types:\n", df.dtypes)

print("\nDescriptive Statistics:\n", df.describe())

print("\nRegion Frequency:\n", df["Region"].value_counts())

plt.figure(figsize=(5,3))
sns.histplot(df["Income"], bins=30, color="Red", edgecolor="black", kde=True)
plt.title("Income Distribution")
plt.xlabel("Income")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(5,3))
sns.boxplot(x=df["Spend"], color="lightgreen")
plt.title("Spend Distribution")
plt.show()

plt.figure(figsize=(5,3))
sns.scatterplot(x="Income", y="Spend", hue="Region", data=df)
plt.title("Income vs Spend")
plt.show()